server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: "${URL_JDBC:jdbc:postgresql://localhost:5432/clean_car}"
    username: "${USER_JDBC:postgres}"
    password: "${PASS_JDBC:admin}"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: car
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    contexts: development
    default-schema: car

security:
  api:
    key: "${SECRET_TOKEN:TESTE_CAR}"
  jwt:
    secret: "${JWT_SECURITY:wF4mI7P+3S9URZdf93sXbB3dM08U91H06uZmwGBCh8rhjz5kH0BzD4KK2y2/YEX0Y6yfiQQ51lYDxYsA2gHZ0A==}"
    expirationMs: 360000

telegram:
  bot:
   token: "${TOKEN_BOT}"
   chat-id: "${ID_BOT}"
   name: "${NAME_BOT}"